name: Deploy in DEV environment

on:
  pull_request:
    branches:
      - 'develop'
  push:
    # branches:
    #   - 'main'

jobs:
  deploy_on_dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Rename environment
        run: |
          sed -i 's/my-react-app/my-react-app-dev/g' package*
          sed -i 's/my-react-app/my-react-app-dev/g' src/App.js
      - name: Get modules and verify dir
        run: |
          npm install
          ls -la