name: CI - Deploy in DEV environment

on:
  pull_request:
    branches:
      - 'develop'
      - 'main'
  push:
    branches:
      - 'develop'
      - 'main'

jobs:
  deploy_on_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Rename environment
        run: |
          sed -i 's/my-react-app/my-react-app-dev/g' package*
          sed -i 's/my-react-app/my-react-app-dev/g' src/App.js

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # caching node_modules
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm test -- --coverage

      - name: Upload Test Coverage
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          path: coverage

      - name: Build
        if: github.event_name == 'push'
        run: npm run build

      - name: Create a Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to staging (my-react-app-dev)
        if: github.event_name == 'push'
        uses: cpina/github-action-push-to-another-repository@v1.6
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'build'
          destination-github-username: 'igorGevaerd'
          destination-repository-name: 'my-react-app-dev'
          target-branch: gh-pages

      - name: Rename environment
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          sed -i 's/my-react-app-dev/my-react-app/g' package*
          sed -i 's/my-react-app-dev/my-react-app/g' src/App.js

      - name: Build
        if: github.event_name == 'push'
        run: npm run build

      - name: Deploy to production (my-react-app)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: cpina/github-action-push-to-another-repository@v1.6
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'build'
          destination-github-username: 'igorGevaerd'
          destination-repository-name: 'my-react-app'
          target-branch: gh-pages